### ISSUE TITLE
Complex Types are not supported by JSON encoder 

### ISSUE THREAD

**Issue by codyolsen** [markphelps/optional#13]
Attempting to marshal/unmarshal Complex64 and Complex128 will throw `json: unsupported type: complex[64/128]` as they are not supported by the JSON encoder.

https://github.com/golang/go/blob/129bb1917b4914f0743ec9b4ef0dfb74df39c07d/src/encoding/json/encode.go#L150

**Comment by markphelps** [comment]
Thanks @codyolsen . Fixed in #16 and released in v0.8.0
